[package]
name = "pass"
version = "0.1.0"
authors = ["Fin Christensen <christensen.fin@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
directories = "3.0.1"
gpgme = "0.9.2"
id_tree = "1.7.0"
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0.22"

[dev-dependencies]
anyhow = "1.0.34"
async-trait = "0.1.42"
futures = "0.3.8"
tempdir = "0.3.7"
tar = "0.4.30"
base64 = "0.13.0"
zstd = "0.5.3"

[dev-dependencies.cucumber_rust]
git = "https://github.com/bbqsrc/cucumber-rust"
branch = "main"
features = ["macros"]

[[test]]
name = "cucumber"
path = "tests/cucumber/mod.rs"
harness = false
